#!/usr/bin/env python3
from __future__ import annotations

import argparse
import csv
import json
import re
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path

from build_repo_path_portability_audit_v1 import DEFAULT_SCAN_ROOTS, iter_scan_files, scan_file


OWNER_BRANCH = "BR-20260429-162"
DEFAULT_OUTPUT_DIR = "/private/tmp/mlpe_field_trial_generated_dependency_review_br162_check"

DETAIL_OUTPUT_NAME = "mlpe_field_trial_generated_dependency_review_v1.csv"
SUMMARY_OUTPUT_NAME = "mlpe_field_trial_generated_dependency_review_summary_v1.csv"
NOTE_OUTPUT_NAME = "mlpe_field_trial_generated_dependency_review_note_v1.md"
JSON_OUTPUT_NAME = "mlpe_field_trial_generated_dependency_review_v1.json"

TARGET_CONTRACTS = {
    "mlpe_upstream_generated_artifact_input",
    "mlpe_chain_directory_bundle_input",
}

DETAIL_COLUMNS = [
    "owner_branch",
    "dependency_id",
    "dependency_contract",
    "source_file",
    "line_no",
    "default_variable",
    "default_path",
    "path_kind",
    "upstream_stage_slug",
    "upstream_branch_hint",
    "upstream_artifact_name",
    "consumer_script",
    "consumer_stage_slug",
    "safe_repo_contract_replacement_flag",
    "requires_upstream_generation_flag",
    "requires_explicit_input_or_manifest_flag",
    "runtime_semantic_change_allowed_flag",
    "recommended_resolution",
    "next_patch_lane",
    "rationale",
]

SUMMARY_COLUMNS = ["owner_branch", "summary_scope", "key", "count"]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Review MLPE field-trial defaults that point to generated upstream artifacts "
            "or chain directory bundles before replacing any temp path defaults."
        )
    )
    parser.add_argument("--repo-root", type=Path, default=Path(__file__).resolve().parents[2])
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT_DIR)
    parser.add_argument("--max-file-bytes", type=int, default=5_000_000)
    return parser.parse_args()


def normalize_text(value: object) -> str:
    text = "" if value is None else str(value).strip()
    return "" if text.lower() == "nan" else text


def resolve(repo_root: Path, value: str | Path) -> Path:
    path = Path(value)
    return path if path.is_absolute() else repo_root / path


def parse_default_variable(context_excerpt: str) -> str:
    match = re.search(r"\b(DEFAULT_[A-Z0-9_]+)\s*=", context_excerpt)
    return match.group(1) if match else ""


def consumer_stage_slug(source_file: str) -> str:
    name = Path(source_file).name
    name = name.removesuffix(".py")
    for prefix in ("build_mlpe_field_trial_", "check_mlpe_field_trial_"):
        if name.startswith(prefix):
            return name.removeprefix(prefix).removesuffix("_v1")
    return name


def upstream_parts(default_path: str) -> tuple[str, str, str, str]:
    path = Path(default_path)
    path_kind = "file_artifact" if path.suffix else "directory_bundle"
    artifact_name = path.name if path_kind == "file_artifact" else ""
    stage_token = path.parent.name if path_kind == "file_artifact" else path.name
    match = re.match(r"(?P<stage>.+)_br(?P<branch>[0-9]+)_check$", stage_token)
    if match:
        return path_kind, match.group("stage"), f"BR-{match.group('branch')}", artifact_name
    return path_kind, stage_token, "", artifact_name


def next_patch_lane(source_file: str, default_path: str) -> str:
    joined = f"{source_file} {default_path}"
    if any(key in joined for key in ("truth_replay", "prepatch_gate")):
        return "mlpe_truth_replay_chain_manifest"
    if any(
        key in joined
        for key in (
            "truth_seed",
            "truth_intake",
            "truth_materialization",
            "common_cause",
            "artifact_mlpe_control",
            "sidecar_truth",
        )
    ):
        return "mlpe_truth_intake_chain_manifest"
    return "mlpe_capture_chain_manifest"


def recommendation(dependency_contract: str) -> tuple[str, str]:
    if dependency_contract == "mlpe_chain_directory_bundle_input":
        return (
            "defer_to_chain_directory_manifest_design",
            "The default points at a bundle directory, so replacing it with a single tracked file would lose directory semantics.",
        )
    return (
        "resolve_from_chain_manifest_or_explicit_input",
        "The default points at an artifact generated by an earlier step; it is not a static contract file.",
    )


def build_review(repo_root: Path, max_file_bytes: int) -> list[dict[str, object]]:
    files, _ = iter_scan_files(repo_root, DEFAULT_SCAN_ROOTS, max_file_bytes)
    audit_rows: list[dict[str, object]] = []
    for path in files:
        audit_rows.extend(scan_file(path, repo_root))

    target_rows = [
        row
        for row in audit_rows
        if normalize_text(row.get("dependency_contract")) in TARGET_CONTRACTS
    ]
    out: list[dict[str, object]] = []
    for idx, row in enumerate(target_rows, start=1):
        source_file = normalize_text(row.get("relative_path"))
        default_path = normalize_text(row.get("matched_text"))
        dependency_contract = normalize_text(row.get("dependency_contract"))
        path_kind, upstream_stage, upstream_branch, artifact_name = upstream_parts(default_path)
        resolution, rationale = recommendation(dependency_contract)
        out.append(
            {
                "owner_branch": OWNER_BRANCH,
                "dependency_id": f"BR162-{idx:03d}",
                "dependency_contract": dependency_contract,
                "source_file": source_file,
                "line_no": int(row.get("line_no", 0)),
                "default_variable": parse_default_variable(normalize_text(row.get("context_excerpt"))),
                "default_path": default_path,
                "path_kind": path_kind,
                "upstream_stage_slug": upstream_stage,
                "upstream_branch_hint": upstream_branch,
                "upstream_artifact_name": artifact_name,
                "consumer_script": Path(source_file).name,
                "consumer_stage_slug": consumer_stage_slug(source_file),
                "safe_repo_contract_replacement_flag": 0,
                "requires_upstream_generation_flag": 1,
                "requires_explicit_input_or_manifest_flag": 1,
                "runtime_semantic_change_allowed_flag": 0,
                "recommended_resolution": resolution,
                "next_patch_lane": next_patch_lane(source_file, default_path),
                "rationale": rationale,
            }
        )
    return out


def summary_rows(review: list[dict[str, object]]) -> list[dict[str, object]]:
    rows = [
        {"owner_branch": OWNER_BRANCH, "summary_scope": "overall", "key": "dependency_rows", "count": len(review)},
        {
            "owner_branch": OWNER_BRANCH,
            "summary_scope": "overall",
            "key": "safe_repo_contract_replacement_rows",
            "count": sum(int(row["safe_repo_contract_replacement_flag"]) for row in review),
        },
        {
            "owner_branch": OWNER_BRANCH,
            "summary_scope": "overall",
            "key": "requires_upstream_generation_rows",
            "count": sum(int(row["requires_upstream_generation_flag"]) for row in review),
        },
        {
            "owner_branch": OWNER_BRANCH,
            "summary_scope": "overall",
            "key": "runtime_semantic_change_allowed_rows",
            "count": sum(int(row["runtime_semantic_change_allowed_flag"]) for row in review),
        },
    ]
    for scope, field in [
        ("dependency_contract", "dependency_contract"),
        ("recommended_resolution", "recommended_resolution"),
        ("next_patch_lane", "next_patch_lane"),
        ("path_kind", "path_kind"),
        ("source_file", "source_file"),
    ]:
        for key, count in sorted(Counter(str(row[field]) for row in review).items()):
            rows.append({"owner_branch": OWNER_BRANCH, "summary_scope": scope, "key": key, "count": count})
    return rows


def write_csv(path: Path, rows: list[dict[str, object]], columns: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8-sig") as f:
        writer = csv.DictWriter(f, fieldnames=columns)
        writer.writeheader()
        for row in rows:
            writer.writerow({col: row.get(col, "") for col in columns})


def write_note(output_dir: Path, summary: list[dict[str, object]]) -> Path:
    lookup = {(row["summary_scope"], row["key"]): row["count"] for row in summary}
    lines = [
        "# MLPE Field-Trial Generated Dependency Review",
        "",
        "## Boundary",
        "- This is a dependency review only; it does not replace generated artifact defaults yet.",
        "- Static template/schema defaults were handled in BR-161.",
        "- User-filled inputs remain explicit/guarded by BR-160.",
        "- Runtime diagnosis semantics and panel-day engine behavior are unchanged.",
        "",
        "## Key Counts",
        f"- dependency rows: {lookup.get(('overall', 'dependency_rows'), 0)}",
        f"- safe repo-contract replacement rows: {lookup.get(('overall', 'safe_repo_contract_replacement_rows'), 0)}",
        f"- requires upstream generation rows: {lookup.get(('overall', 'requires_upstream_generation_rows'), 0)}",
        f"- runtime semantic change allowed rows: {lookup.get(('overall', 'runtime_semantic_change_allowed_rows'), 0)}",
        "",
        "## Recommendation",
        "- Do not convert these defaults to static repo contract files.",
        "- Next patch should introduce an explicit chain manifest or require explicit upstream inputs for selected chain segments.",
    ]
    path = output_dir / NOTE_OUTPUT_NAME
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return path


def main() -> None:
    args = parse_args()
    repo_root = args.repo_root.resolve()
    output_dir = resolve(repo_root, args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    review = build_review(repo_root, args.max_file_bytes)
    summary = summary_rows(review)

    detail_path = output_dir / DETAIL_OUTPUT_NAME
    summary_path = output_dir / SUMMARY_OUTPUT_NAME
    json_path = output_dir / JSON_OUTPUT_NAME
    write_csv(detail_path, review, DETAIL_COLUMNS)
    write_csv(summary_path, summary, SUMMARY_COLUMNS)
    note_path = write_note(output_dir, summary)

    payload = {
        "owner_branch": OWNER_BRANCH,
        "generated_at_utc": datetime.now(timezone.utc).isoformat(),
        "dependency_rows": len(review),
        "dependency_contract_counts": dict(Counter(str(row["dependency_contract"]) for row in review)),
        "next_patch_lane_counts": dict(Counter(str(row["next_patch_lane"]) for row in review)),
        "safe_repo_contract_replacement_rows": sum(int(row["safe_repo_contract_replacement_flag"]) for row in review),
        "requires_upstream_generation_rows": sum(int(row["requires_upstream_generation_flag"]) for row in review),
        "runtime_semantic_change_allowed_rows": sum(int(row["runtime_semantic_change_allowed_flag"]) for row in review),
        "outputs": {
            "detail": str(detail_path),
            "summary": str(summary_path),
            "note": str(note_path),
            "json": str(json_path),
        },
    }
    json_path.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(json.dumps(payload, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
